class Results:
    def __init__ (self):
        self.total_c_hoist1 = []
        self.total_c_ips = []
        self.total_c_hoist2 = []
        self.total_c_hoist = []
        self.costs =  []
        self.num_ips_unroll = []
        self.percentage_hoist1 = []
        self.percentage_ip = []
        self.percentage_hoist2 = []
        self.percentage_all_hoist = []
        self.optimal_h = -1
        self.speedups = []
        self.max_speedup = -1
        self.numkeys_blowup = []
        self.unit_cip = 0
        self.unit_ch1 = 0
        self.unit_ch2 = 0
        self.unit_ch_div_cip = 0
